console.log("THIS A VARIABLE PAGE");
var a=5;let b=6;
let c="HAPPY";
const d="5";
let _a="RK and SK";
console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(_a);
console.log(a+b+c+d+_a);
console.log(a+","+b+","+c+","+d+","+_a);
// var 55a=10; 
// console.log("55a");
console.log(a+b);
console.log(c+_a);
console.log(b+d);
var s=b+d;
console.log(s);
console.log(typeof(s));